Repository uoa-ypec413/metacodenition, pull requests merged in 2022-08, with the labels that each got.

#56 🙋‍♀️ Multiple question support
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/AssignmentFeedbackForm/AssignmentFeedbackForm.tsx
  src/components/AssignmentFeedbackForm/index.tsx
  src/components/ChangeAssignmentButton/ChangeAssignmentButton.tsx
  src/components/ChangeAssignmentButton/index.tsx
  src/components/CodeCopyBox/CodeCopyBox.tsx
  src/components/CodeCopyBox/index.tsx
  src/components/CodeEditor/CodeEditor.tsx
  src/components/CodeInput/CodeInput.tsx
  src/components/NavBar/NavBar.tsx
  src/components/ProblemPopover/ProblemPopover.tsx
  src/components/generics/GenericButton/GenericButton.tsx
  src/context/AssignmentContext.tsx
  src/context/CodeContext.tsx
  src/context/ProblemContext.tsx
  src/hooks/useAssignmentsData.tsx
  src/hooks/useParsons.tsx
  src/hooks/useQuestion.tsx
  src/hooks/useTestCases.tsx
  src/hooks/useUpdate.tsx
  src/index.tsx
  src/pages/ApplicationShell/ApplicationShell.tsx
  src/pages/AssignmentPage/AssignmentPage.tsx
  src/pages/AssignmentPage/index.tsx
  src/pages/AssignmentSubmit/AssignmentSubmit.tsx
  src/pages/AssignmentSubmit/index.tsx
  src/pages/DesignPage/DesignPage.tsx
  src/pages/EvaluationPage/EvaluationPage.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/ProblemPage/ProblemPage.tsx
  src/pages/TestCasePage/TestCasePage.tsx
Labels: enhancement

#65 🔧 Fix notification area clickthrough
  src/components/AppNotifications/AppNotifications.tsx
Labels: bug

#64 🔭 Adjust question tracking
  src/context/AssignmentContext.tsx
  src/hooks/useQuestion.tsx
  src/pages/AssignmentPage/AssignmentPage.tsx
Labels: bug

#68 ✅ Add submission modal
  src/components/NavBar/NavBar.tsx
  src/components/SubmissionModal/SubmissionModal.tsx
  src/components/SubmissionModal/index.tsx
Labels: enhancement

#69 💅 Assignment submission style changes
  src/components/AssignmentFeedbackForm/AssignmentFeedbackForm.tsx
  src/components/CodeCopyBox/CodeCopyBox.tsx
  src/pages/AssignmentSubmit/AssignmentSubmit.tsx
  src/pages/ProblemPage/ProblemPage.tsx
Labels: enhancement

#71 :bug: Fix initial test case
  src/components/TestCaseSolver/TestCaseSolver.tsx
Labels: bug

#78 :speech_balloon: User feedback improvements
  src/components/ChangeAssignmentButton/ChangeAssignmentButton.tsx
  src/components/CodeRunArea/CodeRunArea.tsx
  src/components/CodeRunArea/InputArea.tsx
  src/components/LogOutButton/LogOutButton.tsx
  src/components/NavBar/NavBar.tsx
  src/components/TestCaseSolver/TestCaseSolver.tsx
  src/pages/DesignPage/DesignPage.tsx
  src/pages/EvaluationPage/EvaluationPage.tsx
  src/pages/TestCasePage/TestCasePage.tsx
Labels: enhancement

#79 📔 Track Save State
  src/components/MainLinks/MainLink.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavigationModal/NavigationModal.tsx
  src/components/NavigationModal/index.tsx
  src/context/AssignmentContext.tsx
  src/hooks/useParsons.tsx
  src/pages/DesignPage/DesignPage.tsx
  src/pages/EvaluationPage/EvaluationPage.tsx
  src/pages/TestCasePage/TestCasePage.tsx
Labels: bug, enhancement
